import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(1,process.env.NEXT_PUBLIC_ENV)
  console.log(2,process.env.CUSTOM_ENV)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Test env NEXT_PUBLIC_ENV: {process.env.NEXT_PUBLIC_ENV}</div>
      </main>
    </>
  )
}
