#  call dockerfile
name: Build And Push Docker Image

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "staging or production mode"
        required: true
      folder_name:
        description: "folder used"
        required: true

jobs:
  build-docker-image-and-push-to-gar:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    env:
      VERSION: ${{ github.sha }}
      PROJECT_ID: wide-hulling-226815
      REGISTRY: asia-east1-docker.pkg.dev
      FOLDER_NAME: ${{ github.event.inputs.folder_name }}-management-system
      WORKLOAD_IDENTITY_PROVIDER: projects/910785627085/locations/global/workloadIdentityPools/github-pool/providers/dennnny-provider
      SERVICE_ACCOUNT:  ${{ secrets.SERVICE_ACCOUNT }} 
      MODE: ${{  github.event.inputs.mode  }}
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/${{ env.FOLDER_NAME }}/Dockerfile
          push: true
          build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            NEXTAUTH_SECRET=${{ secrets.NEXT_AUTH_SECRET }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/management-system/${{ env.FOLDER_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/management-system/${{ env.FOLDER_NAME }}:lastet
