name: GitHub Actions For Next.js testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: dependence install
        run: npm ci

      - name: Test
        run: npm run test:ci
  docker-build-and-push:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      VERSION: ${{ github.sha }}
      PROJECT_ID: wide-hulling-226815
      REGISTRY: asia-east1-docker.pkg.dev
      FOLDER_NAME: nextproj
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: ${{secrets.GOOGLE_CREDENTIALS}}
          # workload_identity_provider: ${{secrets.Workload_Identity_Provider}}
          # service_account: ${{secrets.SERVICE_ACCOUNT}}
          # access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/github/${{ env.FOLDER_NAME }}:lastet
