name: Tester Trigger Workflow Dispatch

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/tester/**'
      - 'packages/**'

jobs:
  trigger:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Set production enviornment variable 
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "MODE=production" >> $GITHUB_ENV
      - name: Set staging enviornment variable
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: |
          echo "MODE=staging" >> $GITHUB_ENV
      - name: Invoke workflow with inputs
        uses: actions/trigger-workflow@v1
        with:
          token: ${{ env.GITHUB_ACCESS_TOKEN }}
          event-type: docker
          client-payload: '{"folder_name": "invos", "mode": "${{ env.MODE }}"}'

