name: Tester Trigger Workflow Dispatch

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'apps/tester/**'
      - 'packages/**'

jobs:
  trigger:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow with inputs
        uses: actions/trigger-workflow@v1
        with:
          workflow: docker.yaml
          ref: ${{ github.event.ref }}
          inputs: '{ "folder_name": "tester", "something": true }'
